### ISSUE TITLE
Add support for EchoMimic for lip-syncing with realistic 3D head animations

### ISSUE THREAD

**Issue by jbilcke-hf** [jbilcke-hf/clapper#27]
Ticket specification to be completed..

https://x.com/fffiloni/status/1815424286460354753

(note: we already have some code to call Gradio spaces)

EDIT: humm, I have tested it but it seems to be very slow, and only work on square images. And conventional face poses.

So, I don't know!

**Comment by lalalune** [comment]
This is trivial in ComfyUI, IMO a more robust ComfyUI integration will get these workflows almost for free

**Comment by jbilcke-hf** [comment]
💯  indeed ComfyUI integration can be the answer to a lot of those "how to generate X or Y" questions

**Comment by jbilcke-hf** [comment]
marking as duplicate of https://github.com/jbilcke-hf/clapper/issues/5
