### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lalalune** [jbilcke-hf/clapper#3]
What is the license for this project?

**Comment by jbilcke-hf** [comment]
I'm currently using MIT for the building blocks (webgl timeline, parsers, file format definition etc). The goal is to facilitate the integration into various pipelines and tools by using a permissive licence.

For Clapper the strategy is a bit different, the goal is to become the top end-user app by walking in the footsteps of successful tools such as ComfyUI and Blender, so the licence is going to be GPL (for the same reasons which drove those projects to adopt it)

I will push the commit today to clarify this!

**Comment by jbilcke-hf** [comment]
I have mentioned in the README.md and pushed here:

https://github.com/jbilcke-hf/clapper/blob/main/LICENCE.txt
