### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by mroberts1** [jbilcke-hf/clapper#6]
Install fails on missing script:

```
➜ npm run dev
npm error Missing script: "dev"
```

**Comment by jbilcke-hf** [comment]
hi, it may be an issue with your Node and/or NPM configuration

I recommend to first check that NVM is properly installed:

https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating

Then activate the correct version of Node (`nvm use`)

You can then install the modules (`npm i`)

and finally run the app (`npm run dev`)

**Comment by lalalune** [comment]
I tried this and it worked out of the box, suggesting close
